// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ravmslilgtiimfansiqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhdm1zbGlsZ3RpaW1mYW5zaXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMzk2MDcsImV4cCI6MjA2NzkxNTYwN30.HUMlLkZDrplCu8yR5_clPi2mPJJTPKxrObVMD0olPvA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});